version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password

    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: user
        MYSQL_PASSWORD: user
    volumes:
        - ./init.sql/:/docker-entrypoint-initdb.d/init.sql
        - mydbdata:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
        - 8081:8080
volumes:
  mydbdata: